---
apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  containers:
  - name: helloworld
    image: localhost:5000/hello-world:0.1.0
    ports:
      - containerPort: 8080
